name: helio_yajna_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.*
  - pandas=2.1.*
  - scipy
  - matplotlib
  - seaborn
  - opencv=4.9.*
  - pillow
  - scikit-learn
  - pip:
      - ultralytics==8.3.0
      - roboflow
      - sahi
      - shapely
      - python-dotenv
      - tqdm
      - pyyaml
